name: Belajar Secrets

on:
  push:
    branches:
      - master

jobs:
  Belajar:
    name: Belajar Penggunaan Environment Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Environment Secrets
        run: |
          echo "${{ secrets.MATERI_6 }}" | sed 's/./& /g'
