name: Belajar Secrets

on:
  push:
    branches:
      - master

jobs:
  Belajar:
    name: Belajar Penggunaan Environment Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Using Environment Secrets
        run: |
          echo ${{ secrets.MATERI_8 }} > MATERI_6.txt
          ls
