name: Belajar Secrets

on:
  push:
    branches:
      - master

jobs:
  Belajar:
    name: Belajar Penggunaan Repository Secrets
    runs-on: ubuntu-latest
    
    steps:        
      - name: Using Repository Secrets
        env:
          SPK_SECRET: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo $SPK_SECRET
