name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  my-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build service
        run: |
          docker-compose up -d

  my-cd:
    needs: my-ci
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      
      - name: Create project directory
        run: mkdir -p ~/home/ubuntu/signup-user 
          
      - name: Configure known hosts
        run: |
          ssh-keyscan 108.136.162.224 >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i deploy_key.pem ubuntu@108.136.162.224 
          cd /home/ubuntu/signup-user 
          git init
          git remote add origin https://github.com/rahilwisdom/web-signup-user.git
          git fetch origin
          git checkout master
          git pull origin master
          docker-compose down
          docker-compose up -d
