name: Belajar Secrets

on:
  push:
    branches:
      - master

jobs:
  Belajar:
    name: Belajar Penggunaan Environment Secrets
    runs-on: ubuntu-latest
    environment: Development
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print Environment Secrets
        run: |
          echo "${{ env.MATERI_6 }}"
